### ISSUE TITLE
Clicks Not Recorded Correctly For Inline Elements

### ISSUE THREAD

**Issue by moebrowne** [joestrong/heatmapper#6]
If you click and inline element, for example an `<a/>`, the click position is calculated as 0,0 relative to the document. I assume it's because inline elements don't have a bounding box?

**Comment by joestrong** [comment]
Yeah, inline elements might need a new tactic! :D

**Comment by joestrong** [comment]
I've made a fix here: https://github.com/joestrong/heatmapper/pull/8

Turns out you can't use clientWidth and clientHeight on inline elements, but you can use getClientBoundingBox :+1:

**Comment by joestrong** [comment]
Fix merged in https://github.com/joestrong/heatmapper/pull/8
